# Generated by Django 5.0 on 2023-12-27 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerLogin',
            new_name='customerLoginModel',
        ),
    ]
