# Generated by Django 5.0 on 2023-12-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_rename_customerlogin_customerloginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='registrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_gender', models.CharField(max_length=50)),
                ('service_phone', models.CharField(max_length=50)),
                ('service_email', models.CharField(max_length=50)),
                ('service_password', models.CharField(max_length=50)),
            ],
        ),
    ]
