# Generated by Django 5.0 on 2023-12-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_registrationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='garageLoginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_username', models.CharField(max_length=50)),
                ('service_password', models.CharField(max_length=50)),
            ],
        ),
    ]
