# Generated by Django 5.0 on 2023-12-31 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_claimquerymodel_service_garage_output_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimquerymodel',
            name='service_Garage_Output',
        ),
        migrations.RemoveField(
            model_name='claimquerymodel',
            name='service_ML_Output',
        ),
        migrations.RemoveField(
            model_name='claimquerymodel',
            name='service_username',
        ),
    ]
