# Generated by Django 5.0 on 2023-12-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_claimquerymodel_service_garage_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimquerymodel',
            name='service_Garage_username',
            field=models.CharField(default='garage@gmail.com', max_length=50),
            preserve_default=False,
        ),
    ]
