# Generated by Django 5.0 on 2024-01-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_claimquerymodel_service_garage_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimquerymodel',
            name='service_final_output',
            field=models.CharField(default='Pending', max_length=50),
            preserve_default=False,
        ),
    ]
